### ISSUE TITLE
Handle corrupted images for a re-entrant CLI

### ISSUE THREAD

**Issue by estroz** [RedHatGov/bundle#31] opened 2021-08-11 17:06 UTC
If `oc-bundle` exits during an image download, a partially downloaded layer/image may cause a crash in a subsequent `oc-bundle` run that attempts to start from where the previous run exited. The command should be "smart" enough to clean up these images and restart the download from the previous run's exit point, or at the very least not crash.

**Comment by jpower432** [comment] 2021-09-21 19:00
Closing because this issue has not been able to be replicated. Will reopen if the issue is found again.

**Closed by jpower432** 2021-09-21 19:00 UTC
Labels: bug, wontfix
